id: I8ABCFC36
legacy_id: P001838
ocr_import_info:
  bdrc_scan_id: W22200
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T11:07:22'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:59:15.861404+00:00'
last_modified: 2022-09-02 04:59:29.709779
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22200
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22200
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྟན་པའི་ཉི་མའི་རྣམ་ཐར།
  author: བྱམས་མེ་ལྷ་མཆོག
statistics:
  ocr_word_mean_confidence_index: 0.7765905630726843
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I3542:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3542
      total_pages: 610
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3542.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7765905630726843
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
