id: P001838
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22200
  title: བསྟན་པའི་ཉི་མའི་རྣམ་ཐར
  author: ''
  volumes:
    73b2fcd42336410e849be28183b00071:
      image_group_id: I3542
      title: ''
      volume_number: 1
      total_pages: 610
      base_file: v001.txt
